NewDay/Creative/urls.py
from django.urls import include,path
from . import views
app_name='NewDay'

urlpatterns=[
    path('',views.index,name='index'),
    path('registration/',views.registration,name='registration'),
    path('login/',views.login,name='login'),
    path('home/<int:id>',views.home,name='home'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('changepassword/<int:id>',views.changepassword,name='changepassword'),
    path('logout/',views.logout,name='logout'),
    path('gallery/',views.gallery,name='gallery'),
    path('details/<int:id>',views.details,name='details'),

]

NewDay/NewDay/urls.py
from django.contrib import admin
from django.urls import include,path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Creative.urls'))
]
urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

NewDay/Creative/models.py
from django.db import models

# Create your models here.
class Register(models.Model):
    Name=models.CharField(max_length=10)
    Age=models.IntegerField()
    Place=models.CharField(max_length=10) 
    Photo=models.ImageField(upload_to='media/',null=True,blank=True)
    Email=models.EmailField() 
    Password=models.CharField(max_length=10)

class Gallery(models.Model):
    Brand=models.CharField(max_length=10)
    Name=models.CharField(max_length=10)
    Photo=models.ImageField(upload_to='media/',null=True,blank=True)
    Price=models.IntegerField()

NewDay/Creative/forms.py
from django import forms
from . models import Register

class Registerform(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    Confirmpassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    class Meta():
        model=Register
        fields='__all__'
class Loginform(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    class Meta():
        model=Register
        fields=('Email','Password')

class Updateform(forms.ModelForm):
    class Meta():
        model=Register
        fields=('Name','Age','Place','Email')
        
class ChangepasswordForm(forms.ModelForm):
    Oldpassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    Newpassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    Confirmpassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    class Meta():
        model=Register
        fields=('Oldpassword','Newpassword','Confirmpassword')

NewDay/Creative/views.py
from django.contrib import messages
from django.shortcuts import render,redirect
from django.contrib.auth import logout as logouts
from.models import Register,Gallery
from .forms import Registerform,Loginform,Updateform,ChangepasswordForm

from django.conf import settings
from django.core.mail import send_mail


# Create your views here.
def index(request):
    return render (request,'index.html')

def registration(request):
    if request.method=='POST':
        form=Registerform(request.POST)
        if form.is_valid():
            name=form.cleaned_data['Name']
            age=form.cleaned_data['Age']
            place=form.cleaned_data['Place']
            photo=form.cleaned_data['Photo']
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            confirmpassword=form.cleaned_data['Confirmpassword']

            user=Register.objects.filter(Email=email).exists()  
            if user:
                messages.warning(request,'email already exist')
                return redirect('/login')
            elif password!=confirmpassword:
                messages.success(request,'password missmatch')
            else:
                tab=Register(Name=name,Age=age,Place=place,Photo=photo,Email=email,Password=password)
                tab.save()
                
                
                subject = 'welcome to ewrewrtetgre'
                message = f'Hi {name}, thank you for registering in rgrthytyhrt.'
                email_from = settings.EMAIL_HOST_USER
                recipient_list = [email, ]
                send_mail( subject, message, email_from, recipient_list )

                
                messages.success(request,'DATA SAVED')
                return redirect('/login')
    else:
        form=Registerform()
    return render(request,'registration.html',{'form':form})

def login(request):
    if request.method=='POST':
        form=Loginform(request.POST)
        if form.is_valid():
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            try:
                user=Register.objects.get(Email=email)
                if not user:
                   messages.warning(request,'Email does not exist')
                   return redirect('/login')
                elif password!=user.Password:
                   messages.warning(request,'password incorrect')
                   return redirect,('/login')
                else:
                   messages.success(request,'Success')
                   return redirect('/home/%s' % user.id)
            except:
                messages.warning(request,'email or password incorrect')
                return redirect('/login')
    else:
        form=Loginform()
    return render(request,'login.html',{'form':form})   

def home(request,id):
    user=Register.objects.get(id=id)
    return render(request,'home.html',{'user':user})    

def update(request,id):
    user=Register.objects.get(id=id)
    if request.method=='POST':
        form=Updateform(request.POST or None,instance=user)
        if form.is_valid():
            form.save()
            messages.success(request,'Success')
            return redirect('/home/%s' % user.id)
    else:
        form=Updateform(instance=user)
    return render(request,'update.html',{'user':user,'form':form}) 

def delete(request,id):
    user=Register.objects.get(id=id)
    user.delete()
    messages.success(request,'Success')
    return redirect('/')

def logout(request):
    logouts(request)
    messages.success(request,("logged out"))
    return redirect('/')

def changepassword(request,id):
    user=Register.objects.get(id=id)
    if request.method=='POST':
        form=ChangepasswordForm(request.POST)
        if form.is_valid():
            oldpassword=form.cleaned_data['Oldpassword']
            newpassword=form.cleaned_data['Newpassword']
            confirmpassword=form.cleaned_data['confirmpassword']
            
            if oldpassword!=user.Password:
                messages.warning(request,'incorrect')
                return redirect('/changepassword/%s' % user.id)
            elif oldpassword==newpassword:
                messages.warning(request,'password similar')
                return redirect('/changepassword/%s' % user.id)
            elif newpassword==confirmpassword:
                messages.warning(request,'new password')
                return redirect('/changepassword/%s' % user.id)
            else:
                user.Password=newpassword
                user.save()
                messages.success(request,'change success')
    else:
        form=ChangepasswordForm()
        return render(request,'changepassword.html',{'user':user, 'form':form})            

def gallery(request):
    images=Gallery.objects.all()
    return render(request,'gallery.html',{'images':images})

def details(request,id):
    images=Gallery.objects.get(id=id)
    return render(request,'details.html',{'images':images})
    

               
                
                    

NewDay/templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
    </form>
    <table>
        <tr>
            {{form.as_table}}
        </tr>
    </table>
    <insert type="sumit" value="changepassword"></insert>
</body>
</html>

NewDay/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{images.id}}
    {{images.Brand}}
    {{images.Name}}
    {{images.Price}}
    <img style="width:200px;height:100px;" src="{{images.Photo.url}}">
  
    
</body>
</html>

NewDay/templates/gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table>
        <tr>
            <th>name</th>
            <th>photo</th>
            
        </tr>
        {% for img in images %}
        <tr>
            <td>
                {{img.Name}}
            </td>
            <td><a href="{% url 'NewDay:details' img.id  %}"><img src="{{ img.Photo.url }}" height="100px" width="200px"></a></td>
        </tr>
        {% endfor %}</td>
    </tr>
    </table>
    
</body>

</html>

NewDay/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    {{user.id}}
    {{user.name}}
    <a href="{% url 'NewDay:update' user.id %}">Update</a>
    <a href="{% url 'NewDay:delete' user.id %}">Delete</a>
    <a href="{% url 'NewDay:changepassword' user.id %}">changepassword</a>
    <a href="{% url 'NewDay:logout' %}">Logout</a>
    
    
</body>
</html>

NewDay/templates/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messeges %}
    {{m}}
    {% endfor %}
    <form action="" method="post"></form>
    <a href="{% url 'NewDay:login' %}">Login</a>
    <a href="{% url 'NewDay:gallery' %}">Gallery</a>  
</body>
</html>

NewDay/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messeges %}
    {{m}}
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
             <tr>{{form.as_table}}</tr>
    </table>
    <input type="submit" value="login">
    </form>
    <a href="{% url 'NewDay:registration' %}">Create account</a>
    
</body>
</html>

NewDay/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>{{form.as_table}}</tr>
        </table>    
        <input type="submit" value="submit">
        
    </form>
    
</body>
</html>

NewDay/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>{{form.as_table}}</tr>
        </table>
        <input type="submit" value="update">
    </form>
    
</body>
</html>